version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_housing_v2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: housing_db
    ports:
      - "3307:3306"

