version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_housing
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: housing_db
    ports:
      - "3306:3306"
